steps:
  # build image and push to gcr.io
  - name: "gcr.io/cloud-builders/docker"
    # get latest commit hash
    args: ["build", "-t", "gcr.io/$PROJECT_ID/nginx-cicd:$COMMIT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/nginx-cicd:$COMMIT_SHA"]

  # apply cluster configuration
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "deployment.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-southeast2"
      - "CLOUDSDK_CONTAINER_CLUSTER=nginx-cluster"

  # expose service
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "service.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-southeast2"
      - "CLOUDSDK_CONTAINER_CLUSTER=nginx-cluster"
