apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-cicd
  template:
    metadata:
      labels:
        app: nginx-cicd
    spec:
      containers:
        - name: nginx-container
          image: gcr.io/cc-64-sandbox/nginx-cicd:latest
          ports:
            - containerPort: 80
